# Generated by Django 4.1.1 on 2022-09-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookitem',
            options={'ordering': ['status']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='count',
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='imprint',
            field=models.CharField(help_text='Whrite place where book was placed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', help_text='Status of book in storehouse', max_length=100),
        ),
    ]
